services:
  reservist-digital:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      # Mount das komplette Projekt-Verzeichnis für Live-Updates während der Entwicklung
      - ../:/var/www/html