# Entwicklungs-Features
allowConfigWrite: true  # Ermöglicht direktes Speichern von Konfigurationen

pdfs:
  - name: "Bw5120 - Einverstaendnis zur Ableistung.pdf"
    description: "Einverständniserklärung zur Ableistung von Reservistendienstleistungen"
    category: "Bundeswehr"
  - name: "Bw5120 - Anlage zum Einverstaendnis.pdf"
    description: "Anlage zur Einverständniserklärung zur Ableistung von Reservistendienstleistungen"
    category: "Bundeswehr"
  - name: "Bw5119 - Einverstaendnis Arbeitgeber.pdf"
    description: "Arbeitgeber-Einverständniserklärung zur Ableistung von Reservistendienstleistungen"
    category: "Bundeswehr"    